# Generated by Django 5.0.4 on 2024-06-24 20:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_uk', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_uk', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('sort', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': '8.About',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_uk', models.TextField(null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('sort', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': '7.Banner',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_uk', models.CharField(max_length=255, null=True)),
                ('date', models.CharField(max_length=25)),
                ('date_en', models.CharField(max_length=25, null=True)),
                ('date_uk', models.CharField(max_length=25, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_uk', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('sort', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': '3.Blog',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=50)),
                ('title_en', models.CharField(max_length=50, null=True)),
                ('title_uk', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('description_en', models.TextField(blank=True, max_length=255, null=True)),
                ('description_uk', models.TextField(blank=True, max_length=255, null=True)),
                ('sort', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': '9.Categories',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?(380)?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': '2.Contacts',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_uk', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_uk', models.TextField(null=True)),
                ('price', models.PositiveIntegerField()),
                ('sort', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': '5.Price',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_uk', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_uk', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('sort', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': '4.Reviews',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_uk', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_uk', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('sort', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': '6.Services',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?(380)?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('procedure', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': '1.Sessions',
                'ordering': ['-date_created'],
            },
        ),
    ]
