# Generated by Django 5.0.4 on 2024-05-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
