# Generated by Django 5.0.4 on 2024-05-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('sort', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннери',
                'ordering': ['sort'],
            },
        ),
    ]
