# Generated by Django 5.0.4 on 2024-05-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='banner',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
    ]
