# Generated by Django 5.0.4 on 2024-05-21 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_image_banner_image1_banner_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?(380)?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакти',
                'ordering': ['-date_created'],
            },
        ),
    ]
