# Generated by Django 5.0.4 on 2024-06-21 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['sort'], 'verbose_name': 'About', 'verbose_name_plural': '8.About'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['sort'], 'verbose_name': 'Banner', 'verbose_name_plural': '7.Banner'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['sort'], 'verbose_name': 'Blog', 'verbose_name_plural': '3.Blog'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date_created'], 'verbose_name': 'Contact', 'verbose_name_plural': '2.Contacts'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['sort'], 'verbose_name': 'Price', 'verbose_name_plural': '5.Price'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['sort'], 'verbose_name': 'Review', 'verbose_name_plural': '4.Reviews'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['sort'], 'verbose_name': 'Service', 'verbose_name_plural': '6.Services'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date_created'], 'verbose_name': 'Session', 'verbose_name_plural': '1.Sessions'},
        ),
    ]
