# Generated by Django 5.0.4 on 2024-06-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_about_options_alter_banner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
