# Generated by Django 5.0.4 on 2024-06-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_services_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='category',
        ),
        migrations.AddField(
            model_name='services',
            name='name_category',
            field=models.CharField(blank=True, default='default_category', max_length=100, null=True),
        ),
    ]
