# Generated by Django 5.0.4 on 2024-06-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_services_category_services_name_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='name_category',
        ),
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
