# Generated by Django 5.0.4 on 2024-06-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_services_name_category_services_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
