# Generated by Django 5.0.4 on 2024-06-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_banner_category_remove_banner_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': '1.Category'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date_created'], 'verbose_name': 'Contact', 'verbose_name_plural': '10.Contacts'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date_created'], 'verbose_name': 'Session', 'verbose_name_plural': '11.Sessions'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Subcategory', 'verbose_name_plural': '2.Subcategory'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
