# Generated by Django 5.0.4 on 2024-06-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_category_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='category',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='price',
            name='category',
        ),
        migrations.RemoveField(
            model_name='price',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='category',
        ),
        migrations.RemoveField(
            model_name='services',
            name='category',
        ),
        migrations.RemoveField(
            model_name='services',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='session',
            name='category',
        ),
        migrations.RemoveField(
            model_name='session',
            name='subcategory',
        ),
    ]
