# Generated by Django 5.0.4 on 2024-06-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_session_user_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_uk',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_uk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
