# Generated by Django 5.0.4 on 2024-06-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_about_description_en_about_description_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='date_uk',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
